controllers/NewsController.php
<?php

namespace app\controllers;


use app\models\News;
use stdClass;
use Yii;
use yii\db\Exception;
use yii\web\Controller;

class NewsController extends Controller
{
	/**
	 * @param $action
	 * @return bool
	 * @throws \yii\web\BadRequestHttpException
	 */
	public function beforeAction($action)
	{
		$this->enableCsrfValidation = false;
		return parent::beforeAction($action);
	}
	
	/**
	 * @return string
	 * @throws \yii\db\Exception
	 */
	public function actionEdit()
	{
		$model = new News();
		
		$post = new StdClass();
		
		if (isset($_GET['post_id'])) {
			$post = $model->getOne(strip_tags(trim($_GET['post_id'])));
		} else {
			$post->name = 'No Post';
			$post->description = 'No Description';
		}
		
		
		if (isset($_POST['update']) && $_POST['update'] == strip_tags(trim($_GET['post_id']))) {
			
			$news = $_POST['News'];
			if (!isset($_POST['nonce'])) {
				exit('Abort!');
			}
			
			if (Yii::$app->request->getCsrfToken($_POST['nonce']) === false) {
				exit('Coś poszło nie tak :(. Try again later');
			}
			
			$data = [
				'id' => strip_tags(htmlspecialchars($_POST['update'])),
				'name' => strip_tags(htmlspecialchars($news['name'], ENT_QUOTES, 'UTF-8')),
				'description' => strip_tags(htmlspecialchars($news['description'], ENT_QUOTES, 'UTF-8')),
				'is_active' => strip_tags($news['isActive']),
			];
			
			if (News::instance()->updateNews('news', $data)) {
				AppSessionController::instance()->setFlash('success', 'Post has been updated')
																					->get('success');
			} else {
				AppSessionController::instance()->setFlash('error', 'Oops! Something went wrong :(')
					->get('error');
			}
			
			
			return $this->refresh();
		}
		
		return $this->render('edit', [
			'model' => $model,
			'post' => $post
		]);
	}
	
	/**
	 * @return string|\yii\web\Response
	 * @throws Exception
	 */
	public function actionAdd()
	{
		$model = new News();
		
		if (isset($_POST['authorId'])) {
			if (!isset($_POST['nonce'])) {
				exit('Abort!');
			}
			
			if (Yii::$app->request->getCsrfToken($_POST['nonce']) === false) {
				exit('Coś poszło nie tak :(. Try again later');
			}
			
			$news = $_POST['News'];
			
			$data = [
				'name' => strip_tags(htmlspecialchars($news['name'], ENT_QUOTES, 'UTF-8')),
				'description' => strip_tags(htmlspecialchars($news['description'], ENT_QUOTES, 'UTF-8')),
				'author_id' => strip_tags(htmlspecialchars($_POST['authorId'])),
				'is_active' => strip_tags(htmlspecialchars($news['isActive'], ENT_QUOTES, 'UTF-8')),
			];
			
			News::instance()->addNews('news', $data);
			
			AppSessionController::instance()->setFlash('success', 'Post has been added')->get('success');
			
			return $this->refresh();
		}
		
		return $this->render('add', [
			'model' => $model,
		]);
	}
	
	/**
	 * @return false|string
	 * @throws Exception
	 */
	public function actionDelete()
	{
		if(isset($_POST['delete_post'])) {
			
			$res = [
				'status' => 'success',
				'message' => 'Post was deleted',
				'redirect' => isset($_SERVER['HTTP_REFERER']) ? $_SERVER['HTTP_REFERER'] : Yii::$app->getHomeUrl(),
			];
			
			News::instance()->deleteNews('news', $_POST['delete_post']);
			
			
			echo json_encode($res);
		}
		
		exit();
	}
	
	/**
	 * @return string
	 * @throws Exception
	 */
	public function actionInactive()
	{
		$user = null;
		if (null !== AppSessionController::instance()->get('user')) {
			$user = AppSessionController::instance()->get('user');
		}
		
		$model = News::instance()->getInactiveNews('news', $user['id']);
		
		return $this->render('inactive', [
			'model' => $model,
			'user' => $user,
		]);
	}
}

controllers/UserController.php
<?php

namespace app\controllers;

use app\models\LoginForm;
use app\models\RegisterForm;
use app\models\UserRegister;
use Yii;
use yii\web\Controller;

class UserController extends Controller
{
	public function actionLogout()
	{
		AppSessionController::instance()->remove('user');
		
		return $this->goHome();
	}
	
	/**
	 * @return string|\yii\web\Response
	 * @throws \yii\db\Exception
	 */
	public function actionLogin()
	{
		if (AppSessionController::instance()->get('user') === null) {
			$model = new LoginForm();
			if ($model->load(Yii::$app->request->post()) && $model->login()) {
				if ($model->login()) {
					return $this->goBack();
				}
			} else {
				Yii::$app->session->setFlash('error', 'Login or Password incorrect');
			}
			
			return $this->render('login', [
				'model' => $model,
			]);
			
		}
		
		return $this->goHome();
	}
	
	/**
	 * @return string|Response
	 * @throws \yii\base\Exception
	 * @throws \yii\db\Exception
	 */
	public function actionRegister()
	{
		$model = new RegisterForm();
		
		if ($model->load(Yii::$app->request->post()) && $model->validate()) {
			$model->loadData($_POST['RegisterForm']);
			if (!$model->checkUnique()) {
				
				Yii::$app->session->get('error');
				
				return $this->refresh();
			} else {
				$model->attributes['password'] = Yii::$app->getSecurity()->generatePasswordHash($model->attributes['password'],
																												8);
				$model->attributes['type'] = '2';
				$model->attributes['created_at'] = date('Y-m-d H:i:s');
				$model->attributes['updated_at'] = date('Y-m-d H:i:s');
				
				UserRegister::insertUser('user', $model->attributes);
				
				return $this->redirect(['login']);
			}
		}
		
		return $this->render('register', [
			'model' => $model,
		]);
	}
}

views/layouts/admin.php
<?php
/**
 * @var string $headerAttributes
 * @var string $template
 * @var string $theHeader
 */

use app\controllers\AppSessionController;
use yii\bootstrap\Html;

$user = AppSessionController::instance()->get('user');

?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <base href="/"/>
    <title><?= Html::encode($this->title) ?></title>
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <link rel="stylesheet" href="/assets/bower_components/bootstrap/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="/assets/bower_components/font-awesome/css/font-awesome.min.css">
    <link rel="stylesheet" href="/assets/bower_components/Ionicons/css/ionicons.min.css">
    <link rel="stylesheet" href="/assets/bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css">
    <link rel="stylesheet" href="/assets/dist/css/AdminLTE.min.css">
    <link rel="stylesheet" href="/assets/dist/css/skins/_all-skins.min.css">
    <link type="text/css" rel="stylesheet" href="/assets/css/sweetalert2.min.css">
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

    <!-- Google Font -->
    <link rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
</head>
<body class="hold-transition skin-blue sidebar-mini">
<div class="wrapper">
    <header class="main-header">
        <span class="logo-lg logo"><b>Admin</b></span>
        <nav class="navbar navbar-static-top">
            <div class="navbar-custom-menu">
                <ul class="nav navbar-nav">
                    <li class="dropdown user user-menu">
                        <a class="dropdown-toggle" data-toggle="dropdown">
                            <span class="hidden-xs"><?= Html::encode('Welcome: ' . $user['first_name']) ?></span>
                        </a>
                    </li>
                    <li class="dropdown user user-menu">
                        <a href="/">
							<?= Html::encode('Go to posts'); ?>
                        </a>
                    </li>
                </ul>
            </div>
        </nav>
    </header>
    <div class="content-wrapper">
        <section class="content-header">
            <h1>
				<?= Html::encode('Data Tables') ?>
                <small><?= Html::encode('Preview') ?></small>
            </h1>
        </section>
        <section class="content">
            <div class="row">
                <div class="col-md-12">
					<?php if (null !== Yii::$app->session->getFlash('error')): ?>
                        <div class="alert alert-danger" id="alert">
                            <a class="close" data-dismiss="alert" aria-label="close">&times;</a>
                            <p class="text-center"><strong><?= Yii::$app->session->getFlash('error'); ?></strong></p>
							<?php Yii::$app->session->remove('error'); ?>
                        </div>
					<?php endif; ?>
					<?php if (null !== Yii::$app->session->getFlash('success')): ?>
                        <div class="alert alert-success alert-dismissible" id="alert">
                            <a class="close" data-dismiss="alert" aria-label="close">&times;</a>
                            <p class="text-center"><strong><?= Yii::$app->session->getFlash('success'); ?></strong></p>
							<?php Yii::$app->session->remove('success'); ?>
                        </div>
					<?php endif; ?>
                </div>
            </div>
			<?= $content; ?>
        </section>
    </div>
    <div class="control-sidebar-bg"></div>
</div>
<?php $this->endBody() ?>
<script type="text/javascript">
    deletePost = '/admin/user/delete';
    deletePostTitle = 'Are you sure?';
    deletePostText = 'All posts related to this author will be deleted as well!';
    confirmText = 'Delete Author';
    postRedirect = "<?php echo Yii::$app->request->getAbsoluteUrl() ?>"
</script>
<script src="/assets/js/jquery-1.11.0.min.js"></script>
<script src="/assets/js/bootstrap.js"></script>
<script src="/assets/js/sweetalert2.min.js"></script>
<script src="/assets/js/admin/custom-admin.js"></script>
</body>
</html>
<?php $this->endPage(); ?>

views/layouts/main.php
<?php

/* @var $this \yii\web\View */

/* @var $content string */

use app\widgets\Alert;
use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\web\View;
use yii\widgets\Breadcrumbs;
use app\assets\AppAsset;
use app\controllers\AppSessionController;

AppAsset::register($this);

if (null !== AppSessionController::instance()->get('user')) {
	$user = AppSessionController::instance()->get('user');
	
	$inactive = \app\models\News::instance()->countInactive('news', $user['id']);
}

?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
	<?php $this->registerCsrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
	<?php $this->head() ?>
    <?php $this->registerCssFile('/assets/css/sweetalert2.min.css') ?>
    <!--ADMIN-->
    <?php if (Yii::$app->controller->id == 'admin/user'): ?>
        <?php $this->registerCssFile('/assets/bower_components/bootstrap/dist/css/bootstrap.min.css') ?>
        <?php $this->registerCssFile('/assets/bower_components/font-awesome/css/font-awesome.min.css') ?>
        <?php $this->registerCssFile('/assets/bower_components/Ionicons/css/ionicons.min.css') ?>
        <?php $this->registerCssFile('/assets/bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css') ?>
        <?php $this->registerCssFile('/assets/dist/css/AdminLTE.min.css') ?>
        <?php $this->registerCssFile('/assets/dist/css/skins/_all-skins.min.css') ?>
        <?php $this->registerCssFile('/assets/plugins/iCheck/square/blue.css') ?>
        <link rel="stylesheet"
              href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
    <?php endif; ?>
</head>
<body>
<?php $this->beginBody() ?>

<div class="wrap">
	<?php
	NavBar::begin([
		'brandLabel' => Yii::$app->name,
		'brandUrl' => Yii::$app->homeUrl,
		'options' => [
			'class' => 'navbar-inverse navbar-fixed-top',
		],
	]);
	echo Nav::widget([
		'options' => ['class' => 'navbar-nav navbar-right'],
		'items' => [
			['label' => 'Home', 'url' => ['/site/index']],
			
			empty($user) ? (
				'<li>' . Nav::widget(
					[
						'options' => ['class' => 'navbar-nav navbar-right'],
						'items' => [
							['label' => 'Login', 'url' => ['/user/login']],
						    ['label' => 'Register', 'url' => ['/user/register']]
						]
					]
				) .
                '</li>'
			)
				: (
				'<li>'
				. Html::beginForm(['/user/logout'], 'post')
				. Html::submitButton(
					'Logout (' . $user['first_name'] . ')',
					['class' => 'btn btn-link logout']
				)
				. Html::endForm()
				. '</li>' .
				
				'<li>' . Nav::widget(
					[
						'options' => ['class' => 'navbar-nav navbar-right'],
						'items' => [
							['label' => 'Add New Post', 'url' => ['/news/add']],
                            ['label' => 'Inactive Posts (' . $inactive[0]->posts . ')', 'url' => ['/news/inactive']],
                            ['label' => 'Admin Login', 'url' => ['/admin/user/login']],
						]
					]
				) .
                '</li>'
			)
		]
	]);
	NavBar::end();
	?>

    <div class="container">
		<?= Breadcrumbs::widget([
			'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
		]) ?>
		<?= Alert::widget() ?>
		<?= $content ?>
    </div>
</div>
<footer class="footer">
    <div class="container">
        <p class="pull-left">&copy; Awesome News <?= date('Y') ?></p>

        <p class="pull-right"><?= Yii::powered() ?></p>
    </div>
</footer>


    <?php $this->registerJsFile("/assets/js/sweetalert2.min.js") ?>
    <?php $this->registerJsFile("/assets/bower_components/bootstrap/dist/js/bootstrap.min.js") ?>
    <?php $this->registerJsFile("/assets/plugins/iCheck/icheck.min.js") ?>
<!--Admin-->
<?php if (Yii::$app->controller->id == 'admin/user') : ?>
	<?php $this->registerJs("
        $(function () {
            $('input').iCheck({
                checkboxClass: 'icheckbox_square-blue',
                radioClass: 'iradio_square-blue',
                increaseArea: '20%' // optional
            });
        });
    ") ?>
<?php endif; ?>

<?php $this->endBody() ?>
<?php $this->registerJsVar('
    postRedirect
', '' . (isset($_SERVER['HTTPS']) ? 'https' : 'http' ). "://" . $_SERVER['HTTP_HOST'] . $_SERVER['REQUEST_URI'] . '') ?>
<?php $this->registerJsFile("/assets/js/awesome.js") ?>
</body>
</html>
<?php $this->endPage() ?>